# 100题 1-50

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [104]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [106]:
import numpy as np

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [48]:
print(np.__version__)
np.show_config()

1.19.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [49]:
z10 = np.zeros(10).astype("float64")
z10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [50]:
np.size(z10) * z10.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [51]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [52]:
x1=np.zeros(10)
x1[4]=1

x2 = np.arange(10) == 4
# [False False False False  True False False False False False]
x2 = x2 * 1

x3 = (np.arange(10) == 4).view(np.uint8)

x4 = (np.arange(10) == 4).astype(np.uint8)

x1, x2, x3, x4

(array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8))

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [53]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [54]:
np.arange(0, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [116]:
Z = np.arange(10,19).reshape(3,3).astype(np.uint8)

print(Z)

x_el = Z[[0,1,2],  [0,0,0]]
y_el = Z[[0,0,0],  [0,1,2]]

print("行" + str(x_el))
print("列" + str(y_el))


[[10 11 12]
 [13 14 15]
 [16 17 18]]
行[10 13 16]
列[10 11 12]


> 由el可知
>
> 第0行数据为 10 13 16 第0列数据为 10 11 12
>
> 结论，[][][] -> [dim-3][dim-2][dim-1]

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [127]:
# 方法一
nz = [i for i, v in enumerate(np.array([1,2,0,0,4,0])) if v != 0]
print(str(type(nz)) + " = " + str(nz))

# 方法二
nz = np.nonzero([1,2,0,0,4,0])
print(str(type(nz)) + " = " + str(nz))

<class 'list'> = [0, 1, 4]
<class 'tuple'> = (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [57]:
# 方法一
idm = np.identity(3)
print(idm)

# 方法二
idm = np.eye(3)
print(idm)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [58]:
np.random.random((3,3,3))

array([[[0.18223537, 0.95913864, 0.54062743],
        [0.95826292, 0.52439119, 0.54508057],
        [0.32595694, 0.06589344, 0.05392785]],

       [[0.8673938 , 0.79788613, 0.22871054],
        [0.20419406, 0.84198397, 0.42300113],
        [0.46481114, 0.0628104 , 0.43829985]],

       [[0.50521223, 0.92837152, 0.26182039],
        [0.59906881, 0.70793091, 0.77141258],
        [0.36036288, 0.20867614, 0.84203444]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [59]:
# 方法一，方法二
a13 = np.random.random((10, 10))
print(np.min(a13), a13.min())
print(np.max(a13), a13.max())

0.018484302438798395 0.018484302438798395
0.9676200561700075 0.9676200561700075


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [60]:
# 方法一， 方法二
a14 = np.random.random((30,))
np.mean(a14), a14.mean()

(0.526159248151859, 0.526159248151859)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

新建一个二维数组，边界是1，内部是0

In [61]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

如何给一个存在的数组增加一个边界（比如填充0）

In [62]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [63]:
# 注释为答案

print(0 * np.nan)       # nan
print(np.nan == np.nan) # false
print(np.inf > np.nan)  # false
print(np.nan - np.nan)  # nan
print(np.nan in set([np.nan])) # true
print(0.3 == 3 * 0.1)   # false

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

不太理解这个操作有什么用，欢迎评论

In [64]:
Z = np.diag(1+np.arange(4),k=-1)

print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [65]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [66]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [67]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))

print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [68]:
m12 = np.random.random((5,5))
m12max, m12min = m12.max(), m12.min()
m12 = (m12 - m12min)/(m12max - m12min)
print(m12)

[[0.60339793 0.62223208 0.41591851 0.90222917 0.06555387]
 [0.3451067  0.47504758 0.98855501 0.07134482 0.33300436]
 [0.30410732 1.         0.         0.6941768  0.12939692]
 [0.21729193 0.37090722 0.74083684 0.64873352 0.89201616]
 [0.00992977 0.03639605 0.27982196 0.72990727 0.15849718]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [69]:
color = np.dtype([("r", np.ubyte, (1,)), ("g", np.ubyte, (1,)), ("b", np.ubyte, (1,)), ("a", np.ubyte, (1,))])
print(color)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [70]:
m24 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(m24)
# Alternative solution, in Python 3.5 and above
m24_ = np.ones((5,3)) @ np.ones((3,2))
print(m24_)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [71]:
# Author: Evgeni Burovski
m25 = np.arange(11)
m25[(3 < m25) & (m25 <= 8)] *= -1
print(m25)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [72]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [73]:
Z = np.ones(3)
Z**Z
#2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([1., 1., 1.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [74]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-74-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-74-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [75]:
# Author: Charles R Harris
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))
# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 4.  2. -4.  3. -1.  4. -1. -8. -9. -4.]
[ 4.  2. -4.  3. -1.  4. -1. -8. -9. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [76]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1, Z2)
print(np.intersect1d(Z1,Z2))

[4 4 5 1 1 3 4 5 2 2] [0 4 9 6 5 6 2 9 5 8]
[2 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [77]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0
    
# Back to sanity
_ = np.seterr(**defaults)
Z = np.ones(1) / 0

<ipython-input-77-442f29c0cd2d>:14: RuntimeWarning: divide by zero encountered in true_divide
  Z = np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [78]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-78-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [79]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
today     = np.datetime64('today')
print(today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

2021-03-30
2021-03-31
2021-04-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [80]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [81]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [82]:
Z = np.random.uniform(0,10,3)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[7.10411695 5.26549352 6.90370267]
[7. 5. 6.]
[7. 5. 6.]
[7. 5. 6.]
[7 5 6]
[7. 5. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [83]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [84]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [85]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [86]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.25043137 0.50638121 0.65007462 0.65098419 0.69120502 0.70914834
 0.78722182 0.7914678  0.80564307 0.88060686]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [87]:
# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [88]:
A = np.random.randint(0,2,3)
B = np.random.randint(0,2,3)
print(A, B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 1 1] [1 0 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [89]:
Z = np.zeros(10)
Z.flags.writeable = False
try:
    Z[0] = 1
except Exception as e:
    print(e)

assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [90]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.16980895 0.46082536 0.88702215 0.59178409 1.00181744 0.32129569
 0.96089846 0.99530973 1.20453613 0.54471906]
[1.00301923 1.52052696 1.11646982 1.43303458 0.33210936 1.50659119
 1.355736   0.37365473 0.74280736 0.73561468]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [91]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.78689784 0.45838818 0.79007738 0.009062   0.25657519 0.9007186
 0.7379821  0.         0.60559654 0.92934464]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [92]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [93]:
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [94]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [95]:
np.set_printoptions(threshold=float("inf"))
Z = np.random.random((4,4))
print(Z)

[[0.19549146 0.55033541 0.68400371 0.55654546]
 [0.74604954 0.79255358 0.05126373 0.26876069]
 [0.71051465 0.19429256 0.15488777 0.28756363]
 [0.27901504 0.85293626 0.07683271 0.53803512]]
